# ---------------------------------------------
# Ne pas modifier la valeur de Version.
# ---------------------------------------------
Version: 1

# -------------------------------------------------------------------------------------------------
# Ceci est le prefix avant les messages.
# -------------------------------------------------------------------------------------------------
Prefix: '&6&lzTickets »&f '

# -------------------------------------------------------------------------------------------------
# Ceci est le prefix avant les messages console.
# -------------------------------------------------------------------------------------------------
Log_Prefix: '§7[§9zTickets§7]§f '

# -------------------------------------------------------------------------------------------------
# Quelle LANGUE souhaitez-vous utiliser à partir du fichier localization/messages_LANGUAGE.yml ?
#
# Disponible : "fr" (français), vous pouvez également créer votre propre langue si vous le souhaitez !
# -------------------------------------------------------------------------------------------------
Locale: fr

# -------------------------------------------------------------------------------------------------
# Quels sont les alias de commande pour ce plugin ?
#
# La commande principale est "/zticket".
# -------------------------------------------------------------------------------------------------
Aliases: []

# -------------------------------------------------------------------------------------------------
# Paramètre liè au GUI de confirmation.
# -------------------------------------------------------------------------------------------------
GUIConfirm:
  # -------------------------------------------------------------------------------------------------
  # Si {true} cela activera un gui avant chaque utilisation de ticket.
  # -------------------------------------------------------------------------------------------------
  Enabled: true